version: '1.0'
services:
  app:
    build: ./src
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - JWT_SECRET=secret
      - EMAIL_USER = your_email
      - EMAIL_PASS = your_password
      - CLIENT_URL = http://localhost:3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
